### ISSUE TITLE
miflora-mqtt-daemon gets stuck and requires a reboot of the entire raspberry pi

### ISSUE THREAD

**Issue by AnderssonPeter** [KeesV/kv-home-automation-docker#1]
Hi im running your docker image for [miflora-mqtt-daemon](https://hub.docker.com/r/kverhaar/miflora-mqtt-daemon/) but some times it locks up and just logs the following error message 

Log:
```bash
[2018-08-22 19:35:21] Retrieving data from sensor "Plant6" ...
[2018-08-22 19:35:51] Retrying ...
```

Error log:
```bash
[2018-08-22 19:35:21] Failed to retrieve data from Mi Flora sensor "Plant5" (C4:7C:8D:63:81:C5), success rate: 93%
connect error: Device or resource busy (16)
```

Restarting the container does not help, the only solution i have found is to restart the entire pi.
Do you know of any fix?

I used the following command to create the container `docker run -d --net=host --volume /data/miflora-mqtt-daemon/config.ini:/miflora-mqtt-daemon/config.ini --name miflora --restart always kverhaar/miflora-mqtt-daemon`

and its running hypriot v1.1.1

**Comment by KeesV** [comment]
I'm sorry, I have no idea....
I just used this repo: https://github.com/ThomDietrich/miflora-mqtt-daemon and built a Docker image from that. I see that there's now also a Dockerfile there, so I might remove my version altogether.
I think your best bet is to ask there and see if anyone has an idea.
